# used for testing external secret
{{- if .Values.isTest }}
---
apiVersion: v1
kind: Secret
metadata:
  name: test
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "castai-agent.labels" . | nindent 4 }}
  {{ if gt (len .Values.commonAnnotations) 0 -}}
  annotations:
    {{- include "castai-agent.annotations" . | nindent 4 }}
  {{- end }}
data:
  API_KEY: {{ "test" | b64enc | quote }}
{{- end }}
